server:
    port: 8080

spring:
    datasource:
      hikari:
        auto-commit: false
      url: jdbc:postgresql://localhost:5332/blog_database
      username: user
      password: password
    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show_sql: true
      open-in-view: false
    main:
        web-application-type: servlet
    security:
      user:
        name: admin
        password: admin
    servlet:
      multipart:
        enabled: true
        file-size-threshold: 2KB
        max-file-size: 200MB
        max-request-size: 215MB

logging:
  level:
    org:
      springframework:
        security: DEBUG
